- hosts: lab_nodes
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache web server
      apt:
        name: apache2
        state: present

    - name: Create directory for Apache configuration
      file:
        path: /etc/apache2/sites-available
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Create ansiblesite.conf file
      template:
        src: templates/ansiblesite.conf.j2
        dest: /etc/apache2/sites-available/ansiblesite.conf
        owner: root
        group: root
        mode: '0644'

    - name: Enable Apache site
      command: a2ensite ansiblesite
      args:
        chdir: /etc/apache2/sites-available
        creates: /etc/apache2/sites-enabled/ansiblesite.conf
      notify:
        - Restart Apache service

  handlers:
    - name: Restart Apache service
      service:
        name: apache2
        state: restarted
